### ISSUE TITLE
Drop Amazon Linux 2 in favor of Amazon Linux 2023

### ISSUE THREAD

**Issue by jsf9k** [cisagov/skeleton-ansible-role#131]
# 💡 Summary #

Drop Amazon Linux 2 in favor of Amazon Linux 2023.

## Motivation and context ##

We saw in the last Kraken that it was sometimes necessary to run the Molecule testing job under Ubuntu 20.04, since Amazon Linux 2 has such an ancient version of SystemD (219) that it cannot cope with cgroups v2.  Making this change would obviate the need to run those jobs under the older GitHub Actions runner OS.

[Amazon Linux 2023 was released on March 15, 2023](https://aws.amazon.com/about-aws/whats-new/2023/03/amazon-linux-2023/).

This change will also allow us to unpin the GitHub Actions runner OS for the `test` job on the following repos:
- [cisagov/ansible-role-amazon-efs-utils](https://github.com/cisagov/ansible-role-amazon-efs-utils)
- [cisagov/ansible-role-amazon-ssm-agent](https://github.com/cisagov/ansible-role-amazon-ssm-agent)
- [cisagov/ansible-role-automated-security-updates](https://github.com/cisagov/ansible-role-automated-security-updates)
- [cisagov/ansible-role-cdm-nessus-agent](https://github.com/cisagov/ansible-role-cdm-nessus-agent)
- [cisagov/ansible-role-cdm-tanium-client](https://github.com/cisagov/ansible-role-cdm-tanium-client)
- [cisagov/ansible-role-cloudwatch-agent](https://github.com/cisagov/ansible-role-cloudwatch-agent)
- [cisagov/ansible-role-chrony-aws](https://github.com/cisagov/ansible-role-chrony-aws)
- [cisagov/ansible-role-httpd](https://github.com/cisagov/ansible-role-httpd)
- [cisagov/ansible-role-samba](https://github.com/cisagov/ansible-role-samba)
- [cisagov/ansible-role-vnc-server](https://github.com/cisagov/ansible-role-vnc-server)

**Comment by jsf9k** [comment]
@geerlingguy has not yet created a SystemD-enabled Docker image for Amazon Linux 2022, presumably because it hasn't been officially released yet.  We should either wait for that or create our own Docker image to use in the interim.

**Comment by geerlingguy** [comment]
https://hub.docker.com/repository/docker/geerlingguy/docker-amazonlinux2022-ansible ;)

**Comment by jsf9k** [comment]
> https://hub.docker.com/repository/docker/geerlingguy/docker-amazonlinux2022-ansible ;)

Whoa!  Thanks @geerlingguy!

**Comment by jsf9k** [comment]
Checklist to allow me to track the status of changing the GitHub Actions runner OS for the `test` job:
- [x] cisagov/ansible-role-amazon-efs-utils#42
- [x] cisagov/ansible-role-amazon-ssm-agent#46
- [x] cisagov/ansible-role-automated-security-updates#31
- [x] cisagov/ansible-role-cdm-nessus-agent#47
- [x] cisagov/ansible-role-cdm-tanium-client#48
- [x] cisagov/ansible-role-cloudwatch-agent#49
- [x] cisagov/ansible-role-chrony-aws#35
- [x] cisagov/ansible-role-httpd#44
- [x] cisagov/ansible-role-samba#20
- [x] cisagov/ansible-role-vnc-server#45

**Comment by jsf9k** [comment]
The move to Amazon Linux 2023 was done in #133.  I am currently in the process of updating the GitHub Actions runner OS for the `test` job where necessary.

**Comment by jsf9k** [comment]
> The move to Amazon Linux 2023 was done in #133. I am currently in the process of updating the GitHub Actions runner OS for the `test` job where necessary.

This is now done.  I am just waiting for the PRs to be merged and then I can close this issue.  I also did a search on GitHub to verify that I didn't miss any other repos like these.

**Comment by jsf9k** [comment]
> > The move to Amazon Linux 2023 was done in #133. I am currently in the process of updating the GitHub Actions runner OS for the `test` job where necessary.
> 
> This is now done. I am just waiting for the PRs to be merged and then I can close this issue. I also did a search on GitHub to verify that I didn't miss any other repos like these.

All the relevant PRs have been merged, so this issue can be closed.
